# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 14:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import i18nfield.fields
import klingon.models
import nece.managers
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=190)),
            ],
            bases=(models.Model, klingon.models.Translatable),
        ),
        migrations.CreateModel(
            name='ClassicMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=190)),
            ],
        ),
        migrations.CreateModel(
            name='HvadMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
                'base_manager_name': '_plain_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HvadMovieTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=190)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='movies.HvadMovie')),
            ],
            options={
                'db_table': 'movies_hvadmovie_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='I18nFieldMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('title', i18nfield.fields.I18nCharField(max_length=190)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, nece.managers.TranslationMixin),
        ),
        migrations.CreateModel(
            name='ModeltransMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=190)),
                ('title_af', models.CharField(max_length=190, null=True)),
                ('title_ar', models.CharField(max_length=190, null=True)),
                ('title_ast', models.CharField(max_length=190, null=True)),
                ('title_az', models.CharField(max_length=190, null=True)),
                ('title_bg', models.CharField(max_length=190, null=True)),
                ('title_be', models.CharField(max_length=190, null=True)),
                ('title_bn', models.CharField(max_length=190, null=True)),
                ('title_br', models.CharField(max_length=190, null=True)),
                ('title_bs', models.CharField(max_length=190, null=True)),
                ('title_ca', models.CharField(max_length=190, null=True)),
                ('title_cs', models.CharField(max_length=190, null=True)),
                ('title_cy', models.CharField(max_length=190, null=True)),
                ('title_da', models.CharField(max_length=190, null=True)),
                ('title_de', models.CharField(max_length=190, null=True)),
                ('title_dsb', models.CharField(max_length=190, null=True)),
                ('title_el', models.CharField(max_length=190, null=True)),
                ('title_en', models.CharField(max_length=190, null=True)),
                ('title_en_au', models.CharField(max_length=190, null=True)),
                ('title_en_gb', models.CharField(max_length=190, null=True)),
                ('title_eo', models.CharField(max_length=190, null=True)),
                ('title_es', models.CharField(max_length=190, null=True)),
                ('title_es_ar', models.CharField(max_length=190, null=True)),
                ('title_es_co', models.CharField(max_length=190, null=True)),
                ('title_es_mx', models.CharField(max_length=190, null=True)),
                ('title_es_ni', models.CharField(max_length=190, null=True)),
                ('title_es_ve', models.CharField(max_length=190, null=True)),
                ('title_et', models.CharField(max_length=190, null=True)),
                ('title_eu', models.CharField(max_length=190, null=True)),
                ('title_fa', models.CharField(max_length=190, null=True)),
                ('title_fi', models.CharField(max_length=190, null=True)),
                ('title_fr', models.CharField(max_length=190, null=True)),
                ('title_fy', models.CharField(max_length=190, null=True)),
                ('title_ga', models.CharField(max_length=190, null=True)),
                ('title_gd', models.CharField(max_length=190, null=True)),
                ('title_gl', models.CharField(max_length=190, null=True)),
                ('title_he', models.CharField(max_length=190, null=True)),
                ('title_hi', models.CharField(max_length=190, null=True)),
                ('title_hr', models.CharField(max_length=190, null=True)),
                ('title_hsb', models.CharField(max_length=190, null=True)),
                ('title_hu', models.CharField(max_length=190, null=True)),
                ('title_ia', models.CharField(max_length=190, null=True)),
                ('title_ind', models.CharField(max_length=190, null=True)),
                ('title_io', models.CharField(max_length=190, null=True)),
                ('title_is', models.CharField(max_length=190, null=True)),
                ('title_it', models.CharField(max_length=190, null=True)),
                ('title_ja', models.CharField(max_length=190, null=True)),
                ('title_ka', models.CharField(max_length=190, null=True)),
                ('title_kk', models.CharField(max_length=190, null=True)),
                ('title_km', models.CharField(max_length=190, null=True)),
                ('title_kn', models.CharField(max_length=190, null=True)),
                ('title_ko', models.CharField(max_length=190, null=True)),
                ('title_lb', models.CharField(max_length=190, null=True)),
                ('title_lt', models.CharField(max_length=190, null=True)),
                ('title_lv', models.CharField(max_length=190, null=True)),
                ('title_mk', models.CharField(max_length=190, null=True)),
                ('title_ml', models.CharField(max_length=190, null=True)),
                ('title_mn', models.CharField(max_length=190, null=True)),
                ('title_mr', models.CharField(max_length=190, null=True)),
                ('title_my', models.CharField(max_length=190, null=True)),
                ('title_nb', models.CharField(max_length=190, null=True)),
                ('title_ne', models.CharField(max_length=190, null=True)),
                ('title_nl', models.CharField(max_length=190, null=True)),
                ('title_nn', models.CharField(max_length=190, null=True)),
                ('title_os', models.CharField(max_length=190, null=True)),
                ('title_pa', models.CharField(max_length=190, null=True)),
                ('title_pl', models.CharField(max_length=190, null=True)),
                ('title_pt', models.CharField(max_length=190, null=True)),
                ('title_pt_br', models.CharField(max_length=190, null=True)),
                ('title_ro', models.CharField(max_length=190, null=True)),
                ('title_ru', models.CharField(max_length=190, null=True)),
                ('title_sk', models.CharField(max_length=190, null=True)),
                ('title_sl', models.CharField(max_length=190, null=True)),
                ('title_sq', models.CharField(max_length=190, null=True)),
                ('title_sr', models.CharField(max_length=190, null=True)),
                ('title_sr_latn', models.CharField(max_length=190, null=True)),
                ('title_sv', models.CharField(max_length=190, null=True)),
                ('title_sw', models.CharField(max_length=190, null=True)),
                ('title_ta', models.CharField(max_length=190, null=True)),
                ('title_te', models.CharField(max_length=190, null=True)),
                ('title_th', models.CharField(max_length=190, null=True)),
                ('title_tr', models.CharField(max_length=190, null=True)),
                ('title_tt', models.CharField(max_length=190, null=True)),
                ('title_udm', models.CharField(max_length=190, null=True)),
                ('title_uk', models.CharField(max_length=190, null=True)),
                ('title_ur', models.CharField(max_length=190, null=True)),
                ('title_vi', models.CharField(max_length=190, null=True)),
                ('title_zh_hans', models.CharField(max_length=190, null=True)),
                ('title_zh_hant', models.CharField(max_length=190, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NeceMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('title', models.CharField(max_length=190)),
            ],
            bases=(models.Model, nece.managers.TranslationMixin),
        ),
        migrations.CreateModel(
            name='ParlerMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ParlerMovieTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=190, verbose_name='Title')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='movies.ParlerMovie')),
            ],
            options={
                'verbose_name': 'parler movie Translation',
                'db_table': 'movies_parlermovie_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='parlermovietranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='hvadmovietranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
