# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20170319_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='i18nfieldmovie',
            name='translations',
        ),
    ]
