# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_i18nfieldmovie_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicmovie',
            name='year',
            field=models.IntegerField(default=2001),
            preserve_default=False,
        ),
    ]
